### ISSUE TITLE
{:error, %HTTPoison.Error{id: nil, reason: :timeout}}

### ISSUE THREAD

**Issue by damonvjanis** [tylerwray/elixir-plaid#2]
Fantastic library!! This made it super easy to connect to Plaid and have access to the whole breadth of the API easily.

I'm using it for a really simple app where I basically grab the balance occasionally for a bank account.

All of the token stuff worked great, and the library is intuitive and has great documentation as advertised!

The one thing that didn't work quite right is that when I do a call like the following:
```
Plaid.Accounts.get_balance("valid_token", %{},
      env: :development,
      client_id: "valid_client_id",
      secret: "valid_secret"
    )
```

It times out with the following message:
```
{:error, %HTTPoison.Error{id: nil, reason: :timeout}}
```

I think the fix is to increase the timeout, but right now the HTTP client is tucked under the surface and I can't find a way to change it.

Curious to hear your thoughts on what a good way to expose that would be, I can cut a PR but I think there are a few ways to do it and want to defer to your preference!

**Comment by tylerwray** [comment]
Thanks, @damonvjanis! I have a couple of ideas.

1. I've been thinking about exposing an elixir behaviour that a user of this library could implement to control their own API calls. Either for fine-tuning or if they didn't like HTTPoison. That may be overkill for your roadblock.
2. We could expose an additional `timeout` option on the trailing `config` keyword list that's passed to each function call. I think this would just be a small edit to the `Plaid.Client` module to account for this. Maybe call it `request_timeout` for specificity. 

I'd be okay with either option. Number 2 is much simpler I believe. They both feel clean and understandable to me! I'd accept an MR for either one if you created one. 

I'm also going to create an issue to capture any `HTTPoision.Error` responses we get... I don't wanna expose those from this library 👍🏼 

Thanks for the compliments and well written issue!

**Comment by tylerwray** [comment]
This is now available by passing an `:http_client` option. Closing.
