### ISSUE TITLE
Support for Bank Transfer API

### ISSUE THREAD

**Issue by jtormey** [tylerwray/elixir-plaid#6]
Is there any interest in implementing the bank transfer API while it's still in beta? Happy to help if so!

**Comment by tylerwray** [comment]
100% 🙌🏻  Go for it. Check out the [CONTRIBUTING.md](https://github.com/tylerwray/elixir-plaid/blob/master/CONTRIBUTING.md) file if you haven't already and please let me know if you have any questions.

**Comment by tylerwray** [comment]
Closing this communication as it's not a real "issue"
