### ISSUE TITLE
Invalid Dialyzer warnings for Plaid.LinkToken.User

### ISSUE THREAD

**Issue by jtormey** [tylerwray/elixir-plaid#7]
I'm running into this issue in my project now, where the type definition for `Plaid.LinkToken.User` expects all fields to be strings. This is a problem as some of the fields are optional in the Plaid API and I don't have a use for them, but passing them as `nil` produces a dialyzer warning.

Adding an empty string `""` fixes the type warning, but then the API call to Plaid fails (empty string is not accepted in place of `null`, which makes sense). As a workaround, I've added the following to the top of my context module:

```elixir
  @dialyzer {:nowarn_function, create_link_token: 1}
```

Suggested fix: Update the `Plaid.LinkToken.User` type definition so that keys that are optional in the Plaid API are typed as `String.t() | nil`.

**Comment by tylerwray** [comment]
Fixed with https://github.com/tylerwray/elixir-plaid/pull/8
