### ISSUE TITLE
Identity Match isn't supported

### ISSUE THREAD

**Issue by robacarp** [tylerwray/elixir-plaid#9]
Hey there, not sure if you're still working with this library or not. I've found it useful recently, thank you for what you've provided -- I was able to get Link up and running in minutes. For the Identity product, we decided to go with a Plaid beta product called [Identity Match](https://plaid.com/docs/api/products/identity/#identitymatch) which isn't yet supported here. 

It took a bit longer to get up and running since the response objects weren't present here, but it works fine. If you're interested in adopting the code, I can package it up and open a PR for it.

**Comment by tylerwray** [comment]
Thanks for the praise! ❤️ 

I'd love a PR for that 🙌 Looks like the API's are in their open-api spec - https://github.com/plaid/plaid-openapi - so I feel good about adding the endpoints.
